import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // 클라이언트 컴포넌트 임포트

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* 클라이언트 컴포넌트로 감싸기 */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
